import { productType } from "./types/product";

export const products: productType[] = [
  // Company manufactured products
  {
    id: "own-1",
    name: "Premium Handcrafted Coffee Blend",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { "light-blue": "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description:
      "Our signature house-roasted coffee blend made from carefully selected Arabica beans",
    isOwnProduct: true,
    category: "Coffee",
    inStock: true,
  },
  {
    id: "own-2",
    name: "Specialty Cold Brew Concentrate",
    price: [
      { id: 1, price: "9.99", size: "250", unit: "ml" },
      { id: 2, price: "15.99", size: "500", unit: "ml" },
      { id: 3, price: "20.99", size: "1", unit: "l" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description:
      "Smooth and rich cold brew coffee concentrate made using our proprietary brewing process",
    isOwnProduct: true,
    category: "Coffee",
    inStock: true,
  },
  {
    id: "own-3",
    name: "Limited Edition Seasonal Blend",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description:
      "Small-batch seasonal coffee blend featuring unique flavor profiles",
    isOwnProduct: true,
    category: "Coffee",
    inStock: true,
  },

  // Resale products
  {
    id: "rs-1",
    name: "French Press Coffee Maker",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description: "Classic glass French press for rich, full-bodied coffee",
    isOwnProduct: false,
    category: "Equipment",
    inStock: true,
  },
  {
    id: "rs-2",
    name: "Electric Gooseneck Kettle",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description: "Temperature-controlled kettle perfect for pour-over coffee",
    isOwnProduct: false,
    category: "Equipment",
    inStock: true,
  },
  {
    id: "rs-3",
    name: "Coffee Filter Papers",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description: "Pack of 100 biodegradable filter papers for drip coffee",
    isOwnProduct: false,
    category: "Accessories",
    inStock: true,
  },
  {
    id: "rs-4",
    name: "Coffee Bean Grinder",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description: "Burr grinder for consistent, perfectly ground coffee",
    isOwnProduct: false,
    category: "Equipment",
    inStock: true,
  },
  {
    id: "rs-5",
    name: "Ceramic Coffee Mug Set",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description: "Set of 4 handcrafted ceramic coffee mugs",
    isOwnProduct: false,
    category: "Accessories",
    inStock: true,
  },
  {
    id: "rs-6",
    name: "Coffee Storage Container",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      { default: "/product/teal-ball.jpg" },
      { blue: "/product/blue-ball.jpg" },
      { red: "/product/red-ball.jpg" },
      { yellow: "/product/yellow-ball.jpg" },
      { orange: "/product/orange-ball.jpg" },
    ],
    description: "Airtight container to keep coffee beans fresh",
    isOwnProduct: false,
    category: "Accessories",
    inStock: true,
  },
  {
    id: "rs-7",
    name: "Pour Over Coffee Dripper",
    price: [
      { id: 1, price: "12.99", size: "250", unit: "g" },
      { id: 2, price: "24.99", size: "500", unit: "g" },
      { id: 3, price: "39.99", size: "1", unit: "kg" },
    ],
    images: [
      {
        default: "/product/teal-ball.jpg",
        blue: "/product/blue-ball.jpg",
        red: "/product/red-ball.jpg",
        yellow: "/product/yellow-ball.jpg",
        orange: "/product/orange-ball.jpg",
      },
    ],
    description: "Ceramic pour-over coffee maker for manual brewing",
    isOwnProduct: false,
    category: "Equipment",
    inStock: true,
  },
];
